const string ORGANIZEINVENTORY_CONFIG_ROOT_SERVER = "$profile:OrigemZ\\";
const string ORGANIZEINVENTORY_CONFIG_DIR_SERVER = ORGANIZEINVENTORY_CONFIG_ROOT_SERVER + "OrganizeInventory\\";
const string ORGANIZEINVENTORY_CONFIG_FILENAME = ORGANIZEINVENTORY_CONFIG_DIR_SERVER + "OrganizeInventory.json";